### ISSUE TITLE
Request : Remove DUMMY Objects and Crafts from 3ds in Swicth

### ISSUE THREAD

**Issue by EmmaCoded** [Alexander-Lancellott/MHGU-MHXX-Save-Converter-Script#1]
Since the Petitions are off, I would like to see the possibility of another Fixer, in this case, to remove DUMMY Objects and Crafts from 3ds Objects that are no longer available in Swicth. 
This includes
-Deleted DUMMY images from the Guild Card
![0100770008dd8000_2024-12-01_23-05-13-187](https://github.com/user-attachments/assets/6e559349-05d1-4f73-9447-521f3e6fc757)

-DUMMY box items
![0100770008dd8000_2024-12-01_23-09-34-467](https://github.com/user-attachments/assets/07424e7f-b266-4abe-b280-8e971f95a0bc)

-DUMMY armor crafts
![Capture](https://github.com/user-attachments/assets/dcefc44a-85c6-4e01-8337-1c161b903889)

-Weapon DUMMY Crafts
![0100770008dd8000_2024-12-01_23-09-11-435](https://github.com/user-attachments/assets/1dcc57ff-5f77-4447-a705-311658732741)

-Palico armor DUMMY crafts
![0100770008dd8000_2024-12-01_23-05-50-414](https://github.com/user-attachments/assets/6c7c7d84-a300-43a1-846b-285d9b872146)

-Palico weapon DUMMY crafts
![0100770008dd8000_2024-12-01_23-08-33-987](https://github.com/user-attachments/assets/35b69213-5aa4-4122-a8a1-d38ffe7772b1)

I would say also remove the Weapons, Armor, Palico Weapons, and Palico Armor from box.
But in that case it is not so much of a problem because they can be sold.

I do include the objects because, if they are not removed, the crafting will be unlocked again.

It is also OK to remove all images from the guild card, to avoid a crash, put the first image of the guild card.

**Comment by Alexander-Lancellott** [comment]
Hi, sorry for the delay—this week has been very busy, otherwise, I would have responded sooner. Regarding your request to remove the information considered DUMMY in MHGU, I find it completely unnecessary. Doing so could potentially corrupt important data, and if a user wanted to convert their save back to 3DS format, they would lose that information. Additionally, it would be a headache to identify and locate every DUMMY in the binary structure of the save file.

This is something the user could easily handle themselves by selling the items considered DUMMY. As for the DUMMY images on the Guild Card, none of them have caused any crashes or freezes in my experience. In any case, assuming these DUMMY items cause a crash, the user could resolve the issue by unequipping, replacing or selling any gear (armor, weapons, talismans) of the Hunter and the Palicoes. Regarding the Guild Card, they could simply use the first image or another one that is not considered DUMMY before converting their save file.

To be more specific, I can confirm that this only happens with MHGU and not with MHXX HD Switch Ver.

Unfortunately, I won’t be able to fulfill your request, but I appreciate you taking the time to report this issue, as it could be helpful to others.

**Comment by EmmaCoded** [comment]
Even if what you say is true , I have 2 questions.

-If With The Official Transfer Application , From MHXX To MHXX swicth ver , I Transfer Things , Would The Converter Remove Dummy Objects ? or weapons like the eternal stars in the Japanese Swicth version of the swicth still exist?, I doubt Capcom didn't go to the trouble of removing items from the swicth version and then converting them and not removing the dummy items from the games when transferring from 3ds to swicth, but for that you would have to answer me the key question, do the eternal stars still exist from Monster Hunter Double Cross swicth ver?
-Ok , You say that by selling the Stuff that is solved , But if you already unlocked a Craft , You can't remove it , Or really by selling the Stuff you can remove the DUMMY Crafts (in this case , the ones I had were the ones from the USJ) If you have a way to remove all that , I would appreciate if you tell me

**Comment by Alexander-Lancellott** [comment]
- **Regarding the Official Capcom Transfer Application**:

  I don’t know the exact inner workings of Capcom’s official transfer app, as it is designed to be used only if you have both a 3DS and a Switch. However, there’s a high probability that it removes all DUMMY items, including those in crafting menus and on the Guild Card. The converter I’ve developed is an alternative for cases where you don’t have access to both consoles to perform the official transfer. Naturally, it is more limited in functionality compared to Capcom’s app.

- **Regarding DUMMY Crafts**:

  Unfortunately, once crafting options are unlocked, there is no way to remove them. They will remain in your crafting list unless the save data is manually edited. As I mentioned earlier, identifying and removing DUMMY entries from the save data’s binary structure would be an enormous task. It would require significant effort to remove something that is purely visual and does not affect gameplay or progress. For that reason, I don’t plan on implementing such a feature, and I apologize for not being able to fulfill your request or offer further assistance in this matter.

I appreciate your understanding, and thank you again for taking the time to share your feedback.
